# Site settings
title: SonarQube™ Plugins Index
email: sonarplugins@gmail.com
url: https://www.sonarplugins.com
description: "SonarQube™ Plugins Index site includes a list of all the existing plugins for SonarQube™. Use this site to add new functionalities to your SonarQube™ instance."
skills: "Unleash your SonarQube instance with awesome plugins"
meta_author: Plugins Sonar

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: sonarplugins

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: sonarplugins.com
  location: 
  social: 
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: :title

# additional plugins and gems
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
